version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: proshop_mongo_prod
    restart: always
    volumes:
      - mongo_data_prod:/data/db
    networks:
      - proshop-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: runtime
    container_name: proshop_backend_prod
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/proshop
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - proshop-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/products"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
      args:
        REACT_APP_API_URL: /api
    container_name: proshop_frontend_prod
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - proshop-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mongo_data_prod:

networks:
  proshop-network:
    driver: bridge
