version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: proshop_mongo_dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db
    networks:
      - proshop-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: runtime
    container_name: proshop_backend_dev
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/proshop
      - PORT=5000
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app/backend
      - ./uploads:/app/uploads
      - /app/node_modules
    user: root
    command: sh -c "npm_config_unsafe_perm=true npm install && npx nodemon backend/server.js"
    depends_on:
      - mongo
    networks:
      - proshop-network

  frontend:
    image: node:24-alpine
    container_name: proshop_frontend_dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:5001/api
    user: root
    command: sh -c "npm install && npm start"
    depends_on:
      - backend
    networks:
      - proshop-network

volumes:
  mongo_data_dev:

networks:
  proshop-network:
    driver: bridge
